package com.graphql.warrantydemo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.IOException;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.junit4.SpringRunner;

import com.graphql.spring.boot.test.GraphQLResponse;


@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)
@RunWith(SpringRunner.class)
public class WarrantydemoApplicationTests {

	@Autowired
	private GraphQLTemplate graphQLTemplate;
	
	@Test
	public void fetchWarrantyForAP() throws IOException {
		String authToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyJ9.eyJhdWQiOiI5YzI5NmMzNi0xYjk2LTQ1MWMtOTYzYi0zZWRiNWNmYzJiNDQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9jOTkwYmI3YS01MWY0LTQzOWItYmQzNi05YzA3ZmIxMDQxYzAvIiwiaWF0IjoxNTk4ODcyMTI3LCJuYmYiOjE1OTg4NzIxMjcsImV4cCI6MTU5ODg3NjAyNywiYWlvIjoiRTJCZ1lPaTQvMUR6KzlYaWlJTE1QY3V2WG5CdUFBQT0iLCJhcHBpZCI6ImQ1NTQ3MDNlLWJiZDItNDFlMC1iMTE3LWRiN2UyNzY1YjNiOSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2M5OTBiYjdhLTUxZjQtNDM5Yi1iZDM2LTljMDdmYjEwNDFjMC8iLCJvaWQiOiI1OTZhYzY0OC1hZWU0LTRhZWEtYTM0Yy02ZmZiMDM1MTU3YjIiLCJyaCI6IjAuQUFBQWVydVF5ZlJSbTBPOU5wd0gteEJCd0Q1d1ZOWFN1LUJCc1JmYmZpZGxzN2tTQUFBLiIsInJvbGVzIjpbIm1zbC52aW5sb29rdXAiLCJtc2wudmVoaWNsZWltYWdlIiwibXNsLmFwcHJlY2lhdGlvbiIsIm1zbC5kZWFsZXJvcmNoZXN0cmF0aW9uIiwibXNsLndhcnJhbnR5Y292ZXJhZ2UiLCJtc2wuc2NoZWR1bGVNYWludGVuYW5jZSIsIm1zbC53YXJyYW50eWNhcmQiLCJtc2wuc2NoZWR1bGVtYWludGNhcmQiLCJtc2wucHVibGlzaGVyIiwibXNsLnJlY2FsbCIsIm1zbC5qb3VybmV5IiwibXNsLmZ1ZWwiLCJtc2wuY29uc3VtZXJwcml2YWN5IiwibXNsLm1zcnAiLCJtc2wuc2VydmljZWJvb2tpbmciLCJtc2wudmVoaWNsZWRhdGFzY2hlZHVsZXIiLCJtc2wudmVoaWNsZWltYWdlc2NoZWR1bGVyIiwibXNsLnZlaGljbGVldmVudHF1ZXVlIiwibXNsLnZlaGljbGVpbWFnZS52ZWhpY2xlcHJvZmlsZXN0YXR1cyIsIm1zbC52ZWhpY2xlaW1hZ2UuYmxvYiJdLCJzdWIiOiI1OTZhYzY0OC1hZWU0LTRhZWEtYTM0Yy02ZmZiMDM1MTU3YjIiLCJ0aWQiOiJjOTkwYmI3YS01MWY0LTQzOWItYmQzNi05YzA3ZmIxMDQxYzAiLCJ1dGkiOiJxRlRJcDF0VFRVU2F5QmU5eHNBaUFBIiwidmVyIjoiMS4wIn0.xanEd4CRLWtcJC_w21VmYN5eeCtLtd0jqx7D5zjwKNH084zE3g0L2PGvqowNqbauo1e3ea9yuWHglUMwjlfohb50ROKWCfV0V6287shvWdlZUBevUu9fKQol4GZuM6DgIKOOgBQrnl0Gc8W-EFlJ_sus0w8dHPcWw8gkkyDT7jHXrB4z5wRxhTu01ggPyQSmj5uhNh2uFyHt10gMlLjwjIA9hNRZ1PhUnJshoeudU2lDzEc8shdRqOIkz0I4JeOIaovy51SD5LrexeCFc4OsXU0DqTC4xEnO-qDKo03D_wzMvkR04WDtcLhX8uw7QaNduaPajwLkUmi8BOfmqo7VSA";
		GraphQLResponse response = graphQLTemplate.postForResource("graphql/fetchWarrantyForAp.schema", authToken);
		assertNotNull(response);
        assertTrue(response.isOk());
        assertEquals("Mock plan", response.get("$.data.fetchWarrantyForAp.extendedServicePlan"));
	}




}
